// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DeviceMessages.proto

package com.crustybicycleworks.crustybike;

public final class DeviceMessages {
  private DeviceMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageFromDeviceOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string registration_id = 1;
    boolean hasRegistrationId();
    String getRegistrationId();
    
    // repeated int32 purchase_part_ids = 2;
    java.util.List<java.lang.Integer> getPurchasePartIdsList();
    int getPurchasePartIdsCount();
    int getPurchasePartIds(int index);
  }
  public static final class MessageFromDevice extends
      com.google.protobuf.GeneratedMessage
      implements MessageFromDeviceOrBuilder {
    // Use MessageFromDevice.newBuilder() to construct.
    private MessageFromDevice(Builder builder) {
      super(builder);
    }
    private MessageFromDevice(boolean noInit) {}
    
    private static final MessageFromDevice defaultInstance;
    public static MessageFromDevice getDefaultInstance() {
      return defaultInstance;
    }
    
    public MessageFromDevice getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.crustybicycleworks.crustybike.DeviceMessages.internal_static_CrustyBike_Messages_MessageFromDevice_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.crustybicycleworks.crustybike.DeviceMessages.internal_static_CrustyBike_Messages_MessageFromDevice_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string registration_id = 1;
    public static final int REGISTRATION_ID_FIELD_NUMBER = 1;
    private java.lang.Object registrationId_;
    public boolean hasRegistrationId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getRegistrationId() {
      java.lang.Object ref = registrationId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          registrationId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRegistrationIdBytes() {
      java.lang.Object ref = registrationId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        registrationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated int32 purchase_part_ids = 2;
    public static final int PURCHASE_PART_IDS_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> purchasePartIds_;
    public java.util.List<java.lang.Integer>
        getPurchasePartIdsList() {
      return purchasePartIds_;
    }
    public int getPurchasePartIdsCount() {
      return purchasePartIds_.size();
    }
    public int getPurchasePartIds(int index) {
      return purchasePartIds_.get(index);
    }
    
    private void initFields() {
      registrationId_ = "";
      purchasePartIds_ = java.util.Collections.emptyList();;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getRegistrationIdBytes());
      }
      for (int i = 0; i < purchasePartIds_.size(); i++) {
        output.writeInt32(2, purchasePartIds_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getRegistrationIdBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < purchasePartIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(purchasePartIds_.get(i));
        }
        size += dataSize;
        size += 1 * getPurchasePartIdsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.crustybicycleworks.crustybike.DeviceMessages.MessageFromDevice parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.crustybicycleworks.crustybike.DeviceMessages.MessageFromDevice parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.crustybicycleworks.crustybike.DeviceMessages.MessageFromDevice parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.crustybicycleworks.crustybike.DeviceMessages.MessageFromDevice parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.crustybicycleworks.crustybike.DeviceMessages.MessageFromDevice parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.crustybicycleworks.crustybike.DeviceMessages.MessageFromDevice parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.crustybicycleworks.crustybike.DeviceMessages.MessageFromDevice parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.crustybicycleworks.crustybike.DeviceMessages.MessageFromDevice parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.crustybicycleworks.crustybike.DeviceMessages.MessageFromDevice parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.crustybicycleworks.crustybike.DeviceMessages.MessageFromDevice parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.crustybicycleworks.crustybike.DeviceMessages.MessageFromDevice prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.crustybicycleworks.crustybike.DeviceMessages.MessageFromDeviceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.crustybicycleworks.crustybike.DeviceMessages.internal_static_CrustyBike_Messages_MessageFromDevice_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.crustybicycleworks.crustybike.DeviceMessages.internal_static_CrustyBike_Messages_MessageFromDevice_fieldAccessorTable;
      }
      
      // Construct using com.crustybicycleworks.crustybike.DeviceMessages.MessageFromDevice.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        registrationId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        purchasePartIds_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.crustybicycleworks.crustybike.DeviceMessages.MessageFromDevice.getDescriptor();
      }
      
      public com.crustybicycleworks.crustybike.DeviceMessages.MessageFromDevice getDefaultInstanceForType() {
        return com.crustybicycleworks.crustybike.DeviceMessages.MessageFromDevice.getDefaultInstance();
      }
      
      public com.crustybicycleworks.crustybike.DeviceMessages.MessageFromDevice build() {
        com.crustybicycleworks.crustybike.DeviceMessages.MessageFromDevice result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.crustybicycleworks.crustybike.DeviceMessages.MessageFromDevice buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.crustybicycleworks.crustybike.DeviceMessages.MessageFromDevice result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.crustybicycleworks.crustybike.DeviceMessages.MessageFromDevice buildPartial() {
        com.crustybicycleworks.crustybike.DeviceMessages.MessageFromDevice result = new com.crustybicycleworks.crustybike.DeviceMessages.MessageFromDevice(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.registrationId_ = registrationId_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          purchasePartIds_ = java.util.Collections.unmodifiableList(purchasePartIds_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.purchasePartIds_ = purchasePartIds_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.crustybicycleworks.crustybike.DeviceMessages.MessageFromDevice) {
          return mergeFrom((com.crustybicycleworks.crustybike.DeviceMessages.MessageFromDevice)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.crustybicycleworks.crustybike.DeviceMessages.MessageFromDevice other) {
        if (other == com.crustybicycleworks.crustybike.DeviceMessages.MessageFromDevice.getDefaultInstance()) return this;
        if (other.hasRegistrationId()) {
          setRegistrationId(other.getRegistrationId());
        }
        if (!other.purchasePartIds_.isEmpty()) {
          if (purchasePartIds_.isEmpty()) {
            purchasePartIds_ = other.purchasePartIds_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePurchasePartIdsIsMutable();
            purchasePartIds_.addAll(other.purchasePartIds_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              registrationId_ = input.readBytes();
              break;
            }
            case 16: {
              ensurePurchasePartIdsIsMutable();
              purchasePartIds_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addPurchasePartIds(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string registration_id = 1;
      private java.lang.Object registrationId_ = "";
      public boolean hasRegistrationId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getRegistrationId() {
        java.lang.Object ref = registrationId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          registrationId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRegistrationId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        registrationId_ = value;
        onChanged();
        return this;
      }
      public Builder clearRegistrationId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        registrationId_ = getDefaultInstance().getRegistrationId();
        onChanged();
        return this;
      }
      void setRegistrationId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        registrationId_ = value;
        onChanged();
      }
      
      // repeated int32 purchase_part_ids = 2;
      private java.util.List<java.lang.Integer> purchasePartIds_ = java.util.Collections.emptyList();;
      private void ensurePurchasePartIdsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          purchasePartIds_ = new java.util.ArrayList<java.lang.Integer>(purchasePartIds_);
          bitField0_ |= 0x00000002;
         }
      }
      public java.util.List<java.lang.Integer>
          getPurchasePartIdsList() {
        return java.util.Collections.unmodifiableList(purchasePartIds_);
      }
      public int getPurchasePartIdsCount() {
        return purchasePartIds_.size();
      }
      public int getPurchasePartIds(int index) {
        return purchasePartIds_.get(index);
      }
      public Builder setPurchasePartIds(
          int index, int value) {
        ensurePurchasePartIdsIsMutable();
        purchasePartIds_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addPurchasePartIds(int value) {
        ensurePurchasePartIdsIsMutable();
        purchasePartIds_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllPurchasePartIds(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensurePurchasePartIdsIsMutable();
        super.addAll(values, purchasePartIds_);
        onChanged();
        return this;
      }
      public Builder clearPurchasePartIds() {
        purchasePartIds_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:CrustyBike.Messages.MessageFromDevice)
    }
    
    static {
      defaultInstance = new MessageFromDevice(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:CrustyBike.Messages.MessageFromDevice)
  }
  
  public interface MessageToDeviceOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .CrustyBike.Messages.PartCategory part_categories = 1;
    java.util.List<com.crustybicycleworks.crustybike.DeviceMessages.PartCategory> 
        getPartCategoriesList();
    com.crustybicycleworks.crustybike.DeviceMessages.PartCategory getPartCategories(int index);
    int getPartCategoriesCount();
    java.util.List<? extends com.crustybicycleworks.crustybike.DeviceMessages.PartCategoryOrBuilder> 
        getPartCategoriesOrBuilderList();
    com.crustybicycleworks.crustybike.DeviceMessages.PartCategoryOrBuilder getPartCategoriesOrBuilder(
        int index);
  }
  public static final class MessageToDevice extends
      com.google.protobuf.GeneratedMessage
      implements MessageToDeviceOrBuilder {
    // Use MessageToDevice.newBuilder() to construct.
    private MessageToDevice(Builder builder) {
      super(builder);
    }
    private MessageToDevice(boolean noInit) {}
    
    private static final MessageToDevice defaultInstance;
    public static MessageToDevice getDefaultInstance() {
      return defaultInstance;
    }
    
    public MessageToDevice getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.crustybicycleworks.crustybike.DeviceMessages.internal_static_CrustyBike_Messages_MessageToDevice_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.crustybicycleworks.crustybike.DeviceMessages.internal_static_CrustyBike_Messages_MessageToDevice_fieldAccessorTable;
    }
    
    // repeated .CrustyBike.Messages.PartCategory part_categories = 1;
    public static final int PART_CATEGORIES_FIELD_NUMBER = 1;
    private java.util.List<com.crustybicycleworks.crustybike.DeviceMessages.PartCategory> partCategories_;
    public java.util.List<com.crustybicycleworks.crustybike.DeviceMessages.PartCategory> getPartCategoriesList() {
      return partCategories_;
    }
    public java.util.List<? extends com.crustybicycleworks.crustybike.DeviceMessages.PartCategoryOrBuilder> 
        getPartCategoriesOrBuilderList() {
      return partCategories_;
    }
    public int getPartCategoriesCount() {
      return partCategories_.size();
    }
    public com.crustybicycleworks.crustybike.DeviceMessages.PartCategory getPartCategories(int index) {
      return partCategories_.get(index);
    }
    public com.crustybicycleworks.crustybike.DeviceMessages.PartCategoryOrBuilder getPartCategoriesOrBuilder(
        int index) {
      return partCategories_.get(index);
    }
    
    private void initFields() {
      partCategories_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getPartCategoriesCount(); i++) {
        if (!getPartCategories(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < partCategories_.size(); i++) {
        output.writeMessage(1, partCategories_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < partCategories_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, partCategories_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.crustybicycleworks.crustybike.DeviceMessages.MessageToDevice parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.crustybicycleworks.crustybike.DeviceMessages.MessageToDevice parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.crustybicycleworks.crustybike.DeviceMessages.MessageToDevice parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.crustybicycleworks.crustybike.DeviceMessages.MessageToDevice parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.crustybicycleworks.crustybike.DeviceMessages.MessageToDevice parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.crustybicycleworks.crustybike.DeviceMessages.MessageToDevice parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.crustybicycleworks.crustybike.DeviceMessages.MessageToDevice parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.crustybicycleworks.crustybike.DeviceMessages.MessageToDevice parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.crustybicycleworks.crustybike.DeviceMessages.MessageToDevice parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.crustybicycleworks.crustybike.DeviceMessages.MessageToDevice parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.crustybicycleworks.crustybike.DeviceMessages.MessageToDevice prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.crustybicycleworks.crustybike.DeviceMessages.MessageToDeviceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.crustybicycleworks.crustybike.DeviceMessages.internal_static_CrustyBike_Messages_MessageToDevice_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.crustybicycleworks.crustybike.DeviceMessages.internal_static_CrustyBike_Messages_MessageToDevice_fieldAccessorTable;
      }
      
      // Construct using com.crustybicycleworks.crustybike.DeviceMessages.MessageToDevice.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPartCategoriesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (partCategoriesBuilder_ == null) {
          partCategories_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          partCategoriesBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.crustybicycleworks.crustybike.DeviceMessages.MessageToDevice.getDescriptor();
      }
      
      public com.crustybicycleworks.crustybike.DeviceMessages.MessageToDevice getDefaultInstanceForType() {
        return com.crustybicycleworks.crustybike.DeviceMessages.MessageToDevice.getDefaultInstance();
      }
      
      public com.crustybicycleworks.crustybike.DeviceMessages.MessageToDevice build() {
        com.crustybicycleworks.crustybike.DeviceMessages.MessageToDevice result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.crustybicycleworks.crustybike.DeviceMessages.MessageToDevice buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.crustybicycleworks.crustybike.DeviceMessages.MessageToDevice result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.crustybicycleworks.crustybike.DeviceMessages.MessageToDevice buildPartial() {
        com.crustybicycleworks.crustybike.DeviceMessages.MessageToDevice result = new com.crustybicycleworks.crustybike.DeviceMessages.MessageToDevice(this);
        int from_bitField0_ = bitField0_;
        if (partCategoriesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            partCategories_ = java.util.Collections.unmodifiableList(partCategories_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.partCategories_ = partCategories_;
        } else {
          result.partCategories_ = partCategoriesBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.crustybicycleworks.crustybike.DeviceMessages.MessageToDevice) {
          return mergeFrom((com.crustybicycleworks.crustybike.DeviceMessages.MessageToDevice)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.crustybicycleworks.crustybike.DeviceMessages.MessageToDevice other) {
        if (other == com.crustybicycleworks.crustybike.DeviceMessages.MessageToDevice.getDefaultInstance()) return this;
        if (partCategoriesBuilder_ == null) {
          if (!other.partCategories_.isEmpty()) {
            if (partCategories_.isEmpty()) {
              partCategories_ = other.partCategories_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePartCategoriesIsMutable();
              partCategories_.addAll(other.partCategories_);
            }
            onChanged();
          }
        } else {
          if (!other.partCategories_.isEmpty()) {
            if (partCategoriesBuilder_.isEmpty()) {
              partCategoriesBuilder_.dispose();
              partCategoriesBuilder_ = null;
              partCategories_ = other.partCategories_;
              bitField0_ = (bitField0_ & ~0x00000001);
              partCategoriesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPartCategoriesFieldBuilder() : null;
            } else {
              partCategoriesBuilder_.addAllMessages(other.partCategories_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getPartCategoriesCount(); i++) {
          if (!getPartCategories(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.crustybicycleworks.crustybike.DeviceMessages.PartCategory.Builder subBuilder = com.crustybicycleworks.crustybike.DeviceMessages.PartCategory.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addPartCategories(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .CrustyBike.Messages.PartCategory part_categories = 1;
      private java.util.List<com.crustybicycleworks.crustybike.DeviceMessages.PartCategory> partCategories_ =
        java.util.Collections.emptyList();
      private void ensurePartCategoriesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          partCategories_ = new java.util.ArrayList<com.crustybicycleworks.crustybike.DeviceMessages.PartCategory>(partCategories_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.crustybicycleworks.crustybike.DeviceMessages.PartCategory, com.crustybicycleworks.crustybike.DeviceMessages.PartCategory.Builder, com.crustybicycleworks.crustybike.DeviceMessages.PartCategoryOrBuilder> partCategoriesBuilder_;
      
      public java.util.List<com.crustybicycleworks.crustybike.DeviceMessages.PartCategory> getPartCategoriesList() {
        if (partCategoriesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(partCategories_);
        } else {
          return partCategoriesBuilder_.getMessageList();
        }
      }
      public int getPartCategoriesCount() {
        if (partCategoriesBuilder_ == null) {
          return partCategories_.size();
        } else {
          return partCategoriesBuilder_.getCount();
        }
      }
      public com.crustybicycleworks.crustybike.DeviceMessages.PartCategory getPartCategories(int index) {
        if (partCategoriesBuilder_ == null) {
          return partCategories_.get(index);
        } else {
          return partCategoriesBuilder_.getMessage(index);
        }
      }
      public Builder setPartCategories(
          int index, com.crustybicycleworks.crustybike.DeviceMessages.PartCategory value) {
        if (partCategoriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePartCategoriesIsMutable();
          partCategories_.set(index, value);
          onChanged();
        } else {
          partCategoriesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setPartCategories(
          int index, com.crustybicycleworks.crustybike.DeviceMessages.PartCategory.Builder builderForValue) {
        if (partCategoriesBuilder_ == null) {
          ensurePartCategoriesIsMutable();
          partCategories_.set(index, builderForValue.build());
          onChanged();
        } else {
          partCategoriesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addPartCategories(com.crustybicycleworks.crustybike.DeviceMessages.PartCategory value) {
        if (partCategoriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePartCategoriesIsMutable();
          partCategories_.add(value);
          onChanged();
        } else {
          partCategoriesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addPartCategories(
          int index, com.crustybicycleworks.crustybike.DeviceMessages.PartCategory value) {
        if (partCategoriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePartCategoriesIsMutable();
          partCategories_.add(index, value);
          onChanged();
        } else {
          partCategoriesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addPartCategories(
          com.crustybicycleworks.crustybike.DeviceMessages.PartCategory.Builder builderForValue) {
        if (partCategoriesBuilder_ == null) {
          ensurePartCategoriesIsMutable();
          partCategories_.add(builderForValue.build());
          onChanged();
        } else {
          partCategoriesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addPartCategories(
          int index, com.crustybicycleworks.crustybike.DeviceMessages.PartCategory.Builder builderForValue) {
        if (partCategoriesBuilder_ == null) {
          ensurePartCategoriesIsMutable();
          partCategories_.add(index, builderForValue.build());
          onChanged();
        } else {
          partCategoriesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllPartCategories(
          java.lang.Iterable<? extends com.crustybicycleworks.crustybike.DeviceMessages.PartCategory> values) {
        if (partCategoriesBuilder_ == null) {
          ensurePartCategoriesIsMutable();
          super.addAll(values, partCategories_);
          onChanged();
        } else {
          partCategoriesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearPartCategories() {
        if (partCategoriesBuilder_ == null) {
          partCategories_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          partCategoriesBuilder_.clear();
        }
        return this;
      }
      public Builder removePartCategories(int index) {
        if (partCategoriesBuilder_ == null) {
          ensurePartCategoriesIsMutable();
          partCategories_.remove(index);
          onChanged();
        } else {
          partCategoriesBuilder_.remove(index);
        }
        return this;
      }
      public com.crustybicycleworks.crustybike.DeviceMessages.PartCategory.Builder getPartCategoriesBuilder(
          int index) {
        return getPartCategoriesFieldBuilder().getBuilder(index);
      }
      public com.crustybicycleworks.crustybike.DeviceMessages.PartCategoryOrBuilder getPartCategoriesOrBuilder(
          int index) {
        if (partCategoriesBuilder_ == null) {
          return partCategories_.get(index);  } else {
          return partCategoriesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.crustybicycleworks.crustybike.DeviceMessages.PartCategoryOrBuilder> 
           getPartCategoriesOrBuilderList() {
        if (partCategoriesBuilder_ != null) {
          return partCategoriesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(partCategories_);
        }
      }
      public com.crustybicycleworks.crustybike.DeviceMessages.PartCategory.Builder addPartCategoriesBuilder() {
        return getPartCategoriesFieldBuilder().addBuilder(
            com.crustybicycleworks.crustybike.DeviceMessages.PartCategory.getDefaultInstance());
      }
      public com.crustybicycleworks.crustybike.DeviceMessages.PartCategory.Builder addPartCategoriesBuilder(
          int index) {
        return getPartCategoriesFieldBuilder().addBuilder(
            index, com.crustybicycleworks.crustybike.DeviceMessages.PartCategory.getDefaultInstance());
      }
      public java.util.List<com.crustybicycleworks.crustybike.DeviceMessages.PartCategory.Builder> 
           getPartCategoriesBuilderList() {
        return getPartCategoriesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.crustybicycleworks.crustybike.DeviceMessages.PartCategory, com.crustybicycleworks.crustybike.DeviceMessages.PartCategory.Builder, com.crustybicycleworks.crustybike.DeviceMessages.PartCategoryOrBuilder> 
          getPartCategoriesFieldBuilder() {
        if (partCategoriesBuilder_ == null) {
          partCategoriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.crustybicycleworks.crustybike.DeviceMessages.PartCategory, com.crustybicycleworks.crustybike.DeviceMessages.PartCategory.Builder, com.crustybicycleworks.crustybike.DeviceMessages.PartCategoryOrBuilder>(
                  partCategories_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          partCategories_ = null;
        }
        return partCategoriesBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:CrustyBike.Messages.MessageToDevice)
    }
    
    static {
      defaultInstance = new MessageToDevice(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:CrustyBike.Messages.MessageToDevice)
  }
  
  public interface PartCategoryOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string name = 1;
    boolean hasName();
    String getName();
    
    // repeated .CrustyBike.Messages.Part parts = 2;
    java.util.List<com.crustybicycleworks.crustybike.DeviceMessages.Part> 
        getPartsList();
    com.crustybicycleworks.crustybike.DeviceMessages.Part getParts(int index);
    int getPartsCount();
    java.util.List<? extends com.crustybicycleworks.crustybike.DeviceMessages.PartOrBuilder> 
        getPartsOrBuilderList();
    com.crustybicycleworks.crustybike.DeviceMessages.PartOrBuilder getPartsOrBuilder(
        int index);
  }
  public static final class PartCategory extends
      com.google.protobuf.GeneratedMessage
      implements PartCategoryOrBuilder {
    // Use PartCategory.newBuilder() to construct.
    private PartCategory(Builder builder) {
      super(builder);
    }
    private PartCategory(boolean noInit) {}
    
    private static final PartCategory defaultInstance;
    public static PartCategory getDefaultInstance() {
      return defaultInstance;
    }
    
    public PartCategory getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.crustybicycleworks.crustybike.DeviceMessages.internal_static_CrustyBike_Messages_PartCategory_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.crustybicycleworks.crustybike.DeviceMessages.internal_static_CrustyBike_Messages_PartCategory_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .CrustyBike.Messages.Part parts = 2;
    public static final int PARTS_FIELD_NUMBER = 2;
    private java.util.List<com.crustybicycleworks.crustybike.DeviceMessages.Part> parts_;
    public java.util.List<com.crustybicycleworks.crustybike.DeviceMessages.Part> getPartsList() {
      return parts_;
    }
    public java.util.List<? extends com.crustybicycleworks.crustybike.DeviceMessages.PartOrBuilder> 
        getPartsOrBuilderList() {
      return parts_;
    }
    public int getPartsCount() {
      return parts_.size();
    }
    public com.crustybicycleworks.crustybike.DeviceMessages.Part getParts(int index) {
      return parts_.get(index);
    }
    public com.crustybicycleworks.crustybike.DeviceMessages.PartOrBuilder getPartsOrBuilder(
        int index) {
      return parts_.get(index);
    }
    
    private void initFields() {
      name_ = "";
      parts_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPartsCount(); i++) {
        if (!getParts(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      for (int i = 0; i < parts_.size(); i++) {
        output.writeMessage(2, parts_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      for (int i = 0; i < parts_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, parts_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.crustybicycleworks.crustybike.DeviceMessages.PartCategory parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.crustybicycleworks.crustybike.DeviceMessages.PartCategory parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.crustybicycleworks.crustybike.DeviceMessages.PartCategory parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.crustybicycleworks.crustybike.DeviceMessages.PartCategory parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.crustybicycleworks.crustybike.DeviceMessages.PartCategory parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.crustybicycleworks.crustybike.DeviceMessages.PartCategory parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.crustybicycleworks.crustybike.DeviceMessages.PartCategory parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.crustybicycleworks.crustybike.DeviceMessages.PartCategory parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.crustybicycleworks.crustybike.DeviceMessages.PartCategory parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.crustybicycleworks.crustybike.DeviceMessages.PartCategory parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.crustybicycleworks.crustybike.DeviceMessages.PartCategory prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.crustybicycleworks.crustybike.DeviceMessages.PartCategoryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.crustybicycleworks.crustybike.DeviceMessages.internal_static_CrustyBike_Messages_PartCategory_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.crustybicycleworks.crustybike.DeviceMessages.internal_static_CrustyBike_Messages_PartCategory_fieldAccessorTable;
      }
      
      // Construct using com.crustybicycleworks.crustybike.DeviceMessages.PartCategory.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPartsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (partsBuilder_ == null) {
          parts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          partsBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.crustybicycleworks.crustybike.DeviceMessages.PartCategory.getDescriptor();
      }
      
      public com.crustybicycleworks.crustybike.DeviceMessages.PartCategory getDefaultInstanceForType() {
        return com.crustybicycleworks.crustybike.DeviceMessages.PartCategory.getDefaultInstance();
      }
      
      public com.crustybicycleworks.crustybike.DeviceMessages.PartCategory build() {
        com.crustybicycleworks.crustybike.DeviceMessages.PartCategory result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.crustybicycleworks.crustybike.DeviceMessages.PartCategory buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.crustybicycleworks.crustybike.DeviceMessages.PartCategory result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.crustybicycleworks.crustybike.DeviceMessages.PartCategory buildPartial() {
        com.crustybicycleworks.crustybike.DeviceMessages.PartCategory result = new com.crustybicycleworks.crustybike.DeviceMessages.PartCategory(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (partsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            parts_ = java.util.Collections.unmodifiableList(parts_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.parts_ = parts_;
        } else {
          result.parts_ = partsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.crustybicycleworks.crustybike.DeviceMessages.PartCategory) {
          return mergeFrom((com.crustybicycleworks.crustybike.DeviceMessages.PartCategory)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.crustybicycleworks.crustybike.DeviceMessages.PartCategory other) {
        if (other == com.crustybicycleworks.crustybike.DeviceMessages.PartCategory.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (partsBuilder_ == null) {
          if (!other.parts_.isEmpty()) {
            if (parts_.isEmpty()) {
              parts_ = other.parts_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensurePartsIsMutable();
              parts_.addAll(other.parts_);
            }
            onChanged();
          }
        } else {
          if (!other.parts_.isEmpty()) {
            if (partsBuilder_.isEmpty()) {
              partsBuilder_.dispose();
              partsBuilder_ = null;
              parts_ = other.parts_;
              bitField0_ = (bitField0_ & ~0x00000002);
              partsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPartsFieldBuilder() : null;
            } else {
              partsBuilder_.addAllMessages(other.parts_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        for (int i = 0; i < getPartsCount(); i++) {
          if (!getParts(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              com.crustybicycleworks.crustybike.DeviceMessages.Part.Builder subBuilder = com.crustybicycleworks.crustybike.DeviceMessages.Part.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addParts(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string name = 1;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // repeated .CrustyBike.Messages.Part parts = 2;
      private java.util.List<com.crustybicycleworks.crustybike.DeviceMessages.Part> parts_ =
        java.util.Collections.emptyList();
      private void ensurePartsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          parts_ = new java.util.ArrayList<com.crustybicycleworks.crustybike.DeviceMessages.Part>(parts_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.crustybicycleworks.crustybike.DeviceMessages.Part, com.crustybicycleworks.crustybike.DeviceMessages.Part.Builder, com.crustybicycleworks.crustybike.DeviceMessages.PartOrBuilder> partsBuilder_;
      
      public java.util.List<com.crustybicycleworks.crustybike.DeviceMessages.Part> getPartsList() {
        if (partsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(parts_);
        } else {
          return partsBuilder_.getMessageList();
        }
      }
      public int getPartsCount() {
        if (partsBuilder_ == null) {
          return parts_.size();
        } else {
          return partsBuilder_.getCount();
        }
      }
      public com.crustybicycleworks.crustybike.DeviceMessages.Part getParts(int index) {
        if (partsBuilder_ == null) {
          return parts_.get(index);
        } else {
          return partsBuilder_.getMessage(index);
        }
      }
      public Builder setParts(
          int index, com.crustybicycleworks.crustybike.DeviceMessages.Part value) {
        if (partsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePartsIsMutable();
          parts_.set(index, value);
          onChanged();
        } else {
          partsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setParts(
          int index, com.crustybicycleworks.crustybike.DeviceMessages.Part.Builder builderForValue) {
        if (partsBuilder_ == null) {
          ensurePartsIsMutable();
          parts_.set(index, builderForValue.build());
          onChanged();
        } else {
          partsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addParts(com.crustybicycleworks.crustybike.DeviceMessages.Part value) {
        if (partsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePartsIsMutable();
          parts_.add(value);
          onChanged();
        } else {
          partsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addParts(
          int index, com.crustybicycleworks.crustybike.DeviceMessages.Part value) {
        if (partsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePartsIsMutable();
          parts_.add(index, value);
          onChanged();
        } else {
          partsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addParts(
          com.crustybicycleworks.crustybike.DeviceMessages.Part.Builder builderForValue) {
        if (partsBuilder_ == null) {
          ensurePartsIsMutable();
          parts_.add(builderForValue.build());
          onChanged();
        } else {
          partsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addParts(
          int index, com.crustybicycleworks.crustybike.DeviceMessages.Part.Builder builderForValue) {
        if (partsBuilder_ == null) {
          ensurePartsIsMutable();
          parts_.add(index, builderForValue.build());
          onChanged();
        } else {
          partsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllParts(
          java.lang.Iterable<? extends com.crustybicycleworks.crustybike.DeviceMessages.Part> values) {
        if (partsBuilder_ == null) {
          ensurePartsIsMutable();
          super.addAll(values, parts_);
          onChanged();
        } else {
          partsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearParts() {
        if (partsBuilder_ == null) {
          parts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          partsBuilder_.clear();
        }
        return this;
      }
      public Builder removeParts(int index) {
        if (partsBuilder_ == null) {
          ensurePartsIsMutable();
          parts_.remove(index);
          onChanged();
        } else {
          partsBuilder_.remove(index);
        }
        return this;
      }
      public com.crustybicycleworks.crustybike.DeviceMessages.Part.Builder getPartsBuilder(
          int index) {
        return getPartsFieldBuilder().getBuilder(index);
      }
      public com.crustybicycleworks.crustybike.DeviceMessages.PartOrBuilder getPartsOrBuilder(
          int index) {
        if (partsBuilder_ == null) {
          return parts_.get(index);  } else {
          return partsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.crustybicycleworks.crustybike.DeviceMessages.PartOrBuilder> 
           getPartsOrBuilderList() {
        if (partsBuilder_ != null) {
          return partsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(parts_);
        }
      }
      public com.crustybicycleworks.crustybike.DeviceMessages.Part.Builder addPartsBuilder() {
        return getPartsFieldBuilder().addBuilder(
            com.crustybicycleworks.crustybike.DeviceMessages.Part.getDefaultInstance());
      }
      public com.crustybicycleworks.crustybike.DeviceMessages.Part.Builder addPartsBuilder(
          int index) {
        return getPartsFieldBuilder().addBuilder(
            index, com.crustybicycleworks.crustybike.DeviceMessages.Part.getDefaultInstance());
      }
      public java.util.List<com.crustybicycleworks.crustybike.DeviceMessages.Part.Builder> 
           getPartsBuilderList() {
        return getPartsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.crustybicycleworks.crustybike.DeviceMessages.Part, com.crustybicycleworks.crustybike.DeviceMessages.Part.Builder, com.crustybicycleworks.crustybike.DeviceMessages.PartOrBuilder> 
          getPartsFieldBuilder() {
        if (partsBuilder_ == null) {
          partsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.crustybicycleworks.crustybike.DeviceMessages.Part, com.crustybicycleworks.crustybike.DeviceMessages.Part.Builder, com.crustybicycleworks.crustybike.DeviceMessages.PartOrBuilder>(
                  parts_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          parts_ = null;
        }
        return partsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:CrustyBike.Messages.PartCategory)
    }
    
    static {
      defaultInstance = new PartCategory(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:CrustyBike.Messages.PartCategory)
  }
  
  public interface PartOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 id = 1;
    boolean hasId();
    int getId();
    
    // required string name = 2;
    boolean hasName();
    String getName();
    
    // optional string description = 3;
    boolean hasDescription();
    String getDescription();
    
    // optional bool is_available = 4;
    boolean hasIsAvailable();
    boolean getIsAvailable();
  }
  public static final class Part extends
      com.google.protobuf.GeneratedMessage
      implements PartOrBuilder {
    // Use Part.newBuilder() to construct.
    private Part(Builder builder) {
      super(builder);
    }
    private Part(boolean noInit) {}
    
    private static final Part defaultInstance;
    public static Part getDefaultInstance() {
      return defaultInstance;
    }
    
    public Part getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.crustybicycleworks.crustybike.DeviceMessages.internal_static_CrustyBike_Messages_Part_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.crustybicycleworks.crustybike.DeviceMessages.internal_static_CrustyBike_Messages_Part_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getId() {
      return id_;
    }
    
    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string description = 3;
    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    private java.lang.Object description_;
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          description_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bool is_available = 4;
    public static final int IS_AVAILABLE_FIELD_NUMBER = 4;
    private boolean isAvailable_;
    public boolean hasIsAvailable() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public boolean getIsAvailable() {
      return isAvailable_;
    }
    
    private void initFields() {
      id_ = 0;
      name_ = "";
      description_ = "";
      isAvailable_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, isAvailable_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isAvailable_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.crustybicycleworks.crustybike.DeviceMessages.Part parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.crustybicycleworks.crustybike.DeviceMessages.Part parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.crustybicycleworks.crustybike.DeviceMessages.Part parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.crustybicycleworks.crustybike.DeviceMessages.Part parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.crustybicycleworks.crustybike.DeviceMessages.Part parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.crustybicycleworks.crustybike.DeviceMessages.Part parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.crustybicycleworks.crustybike.DeviceMessages.Part parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.crustybicycleworks.crustybike.DeviceMessages.Part parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.crustybicycleworks.crustybike.DeviceMessages.Part parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.crustybicycleworks.crustybike.DeviceMessages.Part parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.crustybicycleworks.crustybike.DeviceMessages.Part prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.crustybicycleworks.crustybike.DeviceMessages.PartOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.crustybicycleworks.crustybike.DeviceMessages.internal_static_CrustyBike_Messages_Part_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.crustybicycleworks.crustybike.DeviceMessages.internal_static_CrustyBike_Messages_Part_fieldAccessorTable;
      }
      
      // Construct using com.crustybicycleworks.crustybike.DeviceMessages.Part.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        isAvailable_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.crustybicycleworks.crustybike.DeviceMessages.Part.getDescriptor();
      }
      
      public com.crustybicycleworks.crustybike.DeviceMessages.Part getDefaultInstanceForType() {
        return com.crustybicycleworks.crustybike.DeviceMessages.Part.getDefaultInstance();
      }
      
      public com.crustybicycleworks.crustybike.DeviceMessages.Part build() {
        com.crustybicycleworks.crustybike.DeviceMessages.Part result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.crustybicycleworks.crustybike.DeviceMessages.Part buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.crustybicycleworks.crustybike.DeviceMessages.Part result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.crustybicycleworks.crustybike.DeviceMessages.Part buildPartial() {
        com.crustybicycleworks.crustybike.DeviceMessages.Part result = new com.crustybicycleworks.crustybike.DeviceMessages.Part(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.description_ = description_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.isAvailable_ = isAvailable_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.crustybicycleworks.crustybike.DeviceMessages.Part) {
          return mergeFrom((com.crustybicycleworks.crustybike.DeviceMessages.Part)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.crustybicycleworks.crustybike.DeviceMessages.Part other) {
        if (other == com.crustybicycleworks.crustybike.DeviceMessages.Part.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasDescription()) {
          setDescription(other.getDescription());
        }
        if (other.hasIsAvailable()) {
          setIsAvailable(other.getIsAvailable());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              description_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              isAvailable_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 id = 1;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // required string name = 2;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // optional string description = 3;
      private java.lang.Object description_ = "";
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDescription(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
        return this;
      }
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000004);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      void setDescription(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
      }
      
      // optional bool is_available = 4;
      private boolean isAvailable_ ;
      public boolean hasIsAvailable() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public boolean getIsAvailable() {
        return isAvailable_;
      }
      public Builder setIsAvailable(boolean value) {
        bitField0_ |= 0x00000008;
        isAvailable_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsAvailable() {
        bitField0_ = (bitField0_ & ~0x00000008);
        isAvailable_ = false;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:CrustyBike.Messages.Part)
    }
    
    static {
      defaultInstance = new Part(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:CrustyBike.Messages.Part)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CrustyBike_Messages_MessageFromDevice_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CrustyBike_Messages_MessageFromDevice_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CrustyBike_Messages_MessageToDevice_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CrustyBike_Messages_MessageToDevice_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CrustyBike_Messages_PartCategory_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CrustyBike_Messages_PartCategory_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CrustyBike_Messages_Part_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CrustyBike_Messages_Part_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024DeviceMessages.proto\022\023CrustyBike.Messa" +
      "ges\"G\n\021MessageFromDevice\022\027\n\017registration" +
      "_id\030\001 \001(\t\022\031\n\021purchase_part_ids\030\002 \003(\005\"M\n\017" +
      "MessageToDevice\022:\n\017part_categories\030\001 \003(\013" +
      "2!.CrustyBike.Messages.PartCategory\"F\n\014P" +
      "artCategory\022\014\n\004name\030\001 \002(\t\022(\n\005parts\030\002 \003(\013" +
      "2\031.CrustyBike.Messages.Part\"K\n\004Part\022\n\n\002i" +
      "d\030\001 \002(\005\022\014\n\004name\030\002 \002(\t\022\023\n\013description\030\003 \001" +
      "(\t\022\024\n\014is_available\030\004 \001(\010B#\n!com.crustybi" +
      "cycleworks.crustybike"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_CrustyBike_Messages_MessageFromDevice_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_CrustyBike_Messages_MessageFromDevice_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CrustyBike_Messages_MessageFromDevice_descriptor,
              new java.lang.String[] { "RegistrationId", "PurchasePartIds", },
              com.crustybicycleworks.crustybike.DeviceMessages.MessageFromDevice.class,
              com.crustybicycleworks.crustybike.DeviceMessages.MessageFromDevice.Builder.class);
          internal_static_CrustyBike_Messages_MessageToDevice_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_CrustyBike_Messages_MessageToDevice_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CrustyBike_Messages_MessageToDevice_descriptor,
              new java.lang.String[] { "PartCategories", },
              com.crustybicycleworks.crustybike.DeviceMessages.MessageToDevice.class,
              com.crustybicycleworks.crustybike.DeviceMessages.MessageToDevice.Builder.class);
          internal_static_CrustyBike_Messages_PartCategory_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_CrustyBike_Messages_PartCategory_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CrustyBike_Messages_PartCategory_descriptor,
              new java.lang.String[] { "Name", "Parts", },
              com.crustybicycleworks.crustybike.DeviceMessages.PartCategory.class,
              com.crustybicycleworks.crustybike.DeviceMessages.PartCategory.Builder.class);
          internal_static_CrustyBike_Messages_Part_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_CrustyBike_Messages_Part_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CrustyBike_Messages_Part_descriptor,
              new java.lang.String[] { "Id", "Name", "Description", "IsAvailable", },
              com.crustybicycleworks.crustybike.DeviceMessages.Part.class,
              com.crustybicycleworks.crustybike.DeviceMessages.Part.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
